### ISSUE TITLE
Import Fiscal Data Package to Babbage Model

### ISSUE THREAD

**Issue by pwalsh** [openspending/babbage.fiscal-data-package#2]
# Description

As `babbage` will power the first API we expose for OpenSpending Next, we need to have an interface to import Fiscal Data Packages into Babbage (and, the database babbage works from).

# Tasks

* [x] Write loader from Fiscal Data Package to Babbage Model
* [x] Write/design logic for creating tables in the DB backend, which Babbage consumes. See https://github.com/openspending/babbage/issues/4
* [x] Decent unit test coverage, passing on Py 2.7, 3.3, 3.4, 3.5
