### ISSUE TITLE
Database Loader (Lib and Blueprint)

### ISSUE THREAD

**Issue by pwalsh** [openspending/babbage.fiscal-data-package#4]
# Description

The OpenSpending API server needs to be populated. Due to the design of OpenSpending Next, we need a lib responsible for that. This lib just needs to be told the location of a `datapackage.json` and it will load the package into a database that powers the OpenSpending API.

# Tasks

* [x] Write core loading logic as a distinct module (not tied to Flask/HTTP at all)
  * [x] Make sure we use `datapackage-py`, `tabulator-py`, `jsontableschema-py` libs where relevant
* [x] Write a Flask blueprint that exposes the loading logic
  * [x] Requires an endpoint that receives a notification to load
    * [x] Public URL to `datapackage.json`
    * [x] Callback URL for load complete
* [x] Good test coverage
